### ISSUE TITLE
タグとカテゴリーどうするか

### ISSUE THREAD

**Issue by hapicky** [feedforce/tech.feedforce.jp#112]
@tjinjin がブログ記事に `terraform` タグをつけてくれているんだけど、 data/category.yml に追加していなくてテキストがブランクになっている。
追加すればいいんだけど、そうするとフッターのCategoriesにも表示されることになる。
このCategoriesは、投稿が多かったり特徴的なものへの導線にしたいから、全部表示したくはないんだよね...。

なので、
- フッターのCategoriesはタグ全部じゃなくて指定したもの(YAMLで定義？)を表示する
- terraformタグを data/category.yml に追加する
- タグは自由につけてよいことにする
- data/category.yml への追加漏れをCIで気づけるようにする

と考えているんだけど、いいかな？どうかな？

**Comment by tjinjin** [comment]
その設定の存在を知らなかったでござる(´・ω・`)

**Comment by dkimura** [comment]
> terraformタグを data/category.yml に追加する

他にもタグの設定をミスっている記事があったのでやったんですが、
CSSがアレすぎて表示が死にますね。

**Comment by hapicky** [comment]
> 表示が死にますね。

さようか...。

**Comment by tmd45** [comment]
close by #126
