### ISSUE TITLE
いつかある次の技術ブログリニューアルに向けてメモ

### ISSUE THREAD

**Issue by tmd45** [feedforce/tech.feedforce.jp#126]
記事書いてもらいながらいろいろ思いつくけど忘れるので専用スレ立てたった。

気づいたことがあったら思いついたままコメントしてってください。
解決策はここでは議論しなくてよい :octopus: 

見た目の話でも、記事の書きやすさの話でも、内部的な話でも上げておいたらイイと思うよ。

**Comment by tmd45** [comment]
タグとカテゴリー問題。

- [タグとカテゴリーどうするか · Issue #112 · feedforce/tech.feedforce.jp](https://github.com/feedforce/tech.feedforce.jp/issues/112)

**Comment by tmd45** [comment]
code タグのスタイルをどうにかしたい。
いまは middleman のプラグインに従っていて、カスタマイズしづらい。

**Comment by tmd45** [comment]
トップページ（記事一覧）から全文を読む動線が、個人的にちょっとわかりづらい。
「続きを読む」的なものを復活させたほうがよいかも…と思いました。

**Comment by masutaka** [comment]
> 「続きを読む」的なものを復活させたほうがよいかも…と思いました。

読みづらかったのはこれかあ！

**Comment by kano-e** [comment]
> code タグのスタイル

コード量の多い記事書くと背景白の上のコード部分の黒が圧迫感強くて、いつもコードの埋め込みをためらってしまう。

**Comment by tmd45** [comment]
> code タグのスタイル

これ code タグの話じゃなくて pre タグの話でした（syntax hightlight）。
code タグのほうは CSS いじればなんとかなるんですが、現状 pre に合わせてる感じかなと思います。

**Comment by kano-e** [comment]
`div.footnote` の上にもう少し余白が欲しいなーと思いました。
本文と脚注がくっついちゃっているの、読んでいて少ししんどい。

> code タグの話じゃなくて pre タグの話

違う部分の話してた感じですね、あんまり区別してなくて申し訳ない :sweat_drops: 
便乗しちゃった感じで言ったけど "コード量の多い記事書くと背景白の上のコード部分の黒が圧迫感" はいつも気になっているので (特に自分が `文中にコード埋め込みがち` なので) もうちょっと柔らかい雰囲気になると嬉しいなーと思っておりますです。

**Comment by dkimura** [comment]
> トップページ（記事一覧）から全文を読む動線が、個人的にちょっとわかりづらい。
> 「続きを読む」的なものを復活させたほうがよいかも…と思いました。

そもそもタイトルだけでいいのでは感。

> タグとカテゴリー問題。

パーマリンク死ぬけど、「インフラ」「ウェブアプリ（？）」「フロントエンド」とかの大カテゴリーでいいんじゃないかな。。

> Syntax Highlight

何個かThemeは用意されているけど、これっていうのがないというかなんというか…
Middlemanでやらない選択肢もある。
http://prismjs.com/

**Comment by tmd45** [comment]
はてなブログへの移行を推し進めているのでクローズする 😇 
https://feedforce.slack.com/archives/C02R7ECGU/p1507262247000112
