### ISSUE TITLE
サマーインターンのバナーを下ろす

### ISSUE THREAD

**Issue by zenoplex** [feedforce/tech.feedforce.jp#135]
なべはるからの[依頼](https://feedforce.slack.com/archives/creative-team/p1444130364000107)

**Comment by tmd45** [comment]
関連して、たかのさんが過去のバナー追加したコミットを Revert してくだすったPR出来てます→ https://github.com/feedforce/tech.feedforce.jp/pull/134
この対応でいいかどうかご判断いただけたらと思います！

**Comment by tmd45** [comment]
#134 マージ・公開済みなのでこちら Close します :pray:
