### ISSUE TITLE
コードが枠からはみ出す

### ISSUE THREAD

**Issue by masutaka** [feedforce/tech.feedforce.jp#184]
例えば http://tech.feedforce.jp/elasticache.html

![elasticache cloudwatch_fluentd_zabbix ___feedforce_engineers__blog](https://cloud.githubusercontent.com/assets/170014/13733232/79e67562-e9d3-11e5-8e84-878ad69de121.png)

Firefox 44.0 と 45.0、Chrome 49.0.2623.87 (64-bit) で再現した。
Chrome  48.0.2564.116 (64-bit) では再現しない。

関連チャット: https://feedforce.slack.com/archives/tech-blog/p1457802864000002

**Comment by tmd45** [comment]
CSS ヒント :memo:

- [[CSS]テキストが長いとレイアウトが崩れる！予期せぬコンテンツに対応するためのスタイルシートのテクニック | コリス](http://coliss.com/articles/build-websites/operation/css/css-techniques-for-unexpected-content.html)

**Comment by tmd45** [comment]
close by #126
